import { ClerkProvider } from '@clerk/nextjs'
import '../globals.css'
import { Inter } from 'next/font/google'
import Sidebar from '@/components/menu/Sidebar'
import Topbar from '@/components/menu/Topbar'
import MobileNav from '@/components/menu/MobileNav'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          
          <div className='sm:hidden'>
            <Topbar />
          </div>

          <div>
            <div className='max-sm:hidden'>
              <Sidebar />
            </div>
            {children}
          </div>

          <div className='sm:hidden'>
            <MobileNav />
          </div>

        </body>
      </html>
    </ClerkProvider>
  )
}
